services:
  sourcegraph:
    image: sourcegraph/server:6.10.3349-patched
    ports:
      - "7080:7080"
    environment:
      - ALLOW_SINGLE_DOCKER_CODE_INSIGHTS=true
    volumes:
      - sg-config:/etc/sourcegraph
      - sg-data:/var/opt/sourcegraph
      - ~/.sourcegraph-config/gitconfig:/etc/gitconfig:ro
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped

networks:
  default:
    external: true
    name: infra

volumes:
  sg-config:
  sg-data:
